import Foundation
import PaintKit

/// Builds the GitHub social card from assets generated by this repository.
///
/// The right side is a real Release-window capture, and the icon is the
/// PaintKit-generated app icon. Keeping the composition here makes the public
/// image reproducible instead of leaving a hand-edited marketing file behind.
@MainActor
enum SocialPreview {
    enum PreviewError: LocalizedError {
        case missingIcon
        case scalingFailed

        var errorDescription: String? {
            switch self {
            case .missingIcon:
                "The generated 1024px app icon is missing."
            case .scalingFailed:
                "The source artwork could not be scaled."
            }
        }
    }

    static func run(windowCapture: URL, output: URL) throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        let iconURL = root.appendingPathComponent(
            "App/Resources/Assets.xcassets/AppIcon.appiconset/icon_512x512@2x.png"
        )
        guard FileManager.default.fileExists(atPath: iconURL.path) else {
            throw PreviewError.missingIcon
        }

        let window = try ImageCodec.decode(contentsOf: windowCapture)
        let icon = try ImageCodec.decode(contentsOf: iconURL)
        guard let windowScaled = ImageTransform.scaled(
            window, to: (696, 448), using: .smooth
        ), let iconScaled = ImageTransform.scaled(
            icon, to: (96, 96), using: .smooth
        ) else {
            throw PreviewError.scalingFailed
        }

        func colour(_ hex: String) -> PaintColour { PaintColour(hex: hex) ?? .white }

        var canvas = Bitmap(width: 1280, height: 640, fill: colour("151922").rgba8)
        canvas.composite(iconScaled, at: PixelPoint(x: 72, y: 64))
        canvas.composite(windowScaled, at: PixelPoint(x: 520, y: 96))

        TextRenderer.draw(
            "ItsPaint",
            in: PixelRect(x: 72, y: 184, width: 410, height: 78),
            style: TextRenderer.Style(
                fontName: "Helvetica-Bold",
                pointSize: 62,
                colour: colour("FFFFFF")
            ),
            into: &canvas
        )
        TextRenderer.draw(
            "A focused paint app",
            in: PixelRect(x: 74, y: 286, width: 430, height: 46),
            style: TextRenderer.Style(
                fontName: "Helvetica",
                pointSize: 30,
                colour: colour("D8DEE9")
            ),
            into: &canvas
        )
        TextRenderer.draw(
            "for macOS.",
            in: PixelRect(x: 74, y: 334, width: 430, height: 46),
            style: TextRenderer.Style(
                fontName: "Helvetica",
                pointSize: 30,
                colour: colour("D8DEE9")
            ),
            into: &canvas
        )
        TextRenderer.draw(
            "Native macOS  ·  12 tools  ·  zero dependencies",
            in: PixelRect(x: 74, y: 430, width: 440, height: 36),
            style: TextRenderer.Style(
                fontName: "Helvetica",
                pointSize: 17,
                colour: colour("9BA7B5")
            ),
            into: &canvas
        )

        try ImageCodec.write(canvas, to: output, as: .png)
        print("Wrote 1280×640 social preview to \(output.path)")
    }
}
